#version: '2'
services:
  notebook:
    build: 
       context: .
       dockerfile: ./Dockerfile
    #image: pytorch-docker/pytorch-gpu-jupyter
    #image: nvidia-docker/pytorch-gpu-jupyter
    expose:
      - 8080
      - 22
    container_name: jupyter_pytorch
    labels:
      description: Jupyter Notebooks and Jupyter Lab
      name: jupyter notebook and jupyter lab
    ports:
      - ${PORT}:8888
    volumes:
      - ${WORKING_DIR}:/workspace
    runtime: nvidia
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      #JUPYTER_TOKEN: "docker"
    #command: bash -c "sh /etc/init.d/ssh start"
    #command: bash -c "jupyter serverextension enable --py jupyter_http_over_ws"
    #command: bash -c "jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --port=8888 --NotebookApp.allow_origin='https://colab.research.google.com' --NotebookApp.port_retries=0 --NotebookApp.token='' --NotebookApp.password=''"
    #command: bash -c "jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --port=8888"
    command: bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"